version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    build:
      context: . # Dockerfile이 위치한 디렉터리
      dockerfile: Dockerfile # 사용할 Dockerfile 이름
    container_name: jenkins
    ports:
      - "18080:8080" # Jenkins Web UI
      - "50000:50000" # Jenkins JNLP agents
    volumes:
      - ../jenkins_home:/var/jenkins_home # Jenkins data 저장
      - D:/PROJECT/web:/var/jenkins_home/web
      - /var/run/docker.sock:/var/run/docker.sock # Docker 실행을 위해 Docker socket 공유
    restart: always