version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "18080:8080" # Jenkins Web UI
      - "50000:50000" # Jenkins JNLP agents
    volumes:
      - ../jenkins_home:/var/jenkins_home # Jenkins data 저장
      - /var/run/docker.sock:/var/run/docker.sock # Docker 실행을 위해 Docker socket 공유
    restart: always
